# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-12-18 23:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20251219_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('job', models.CharField(max_length=100, verbose_name='Род занятий')),
                ('gender', models.CharField(choices=[('1', 'Мужской'), ('2', 'Женский')], max_length=10, verbose_name='Пол')),
                ('design', models.CharField(choices=[('1', 'Отлично'), ('2', 'Хорошо'), ('3', 'Сойдет'), ('4', 'Ужасно')], max_length=20, verbose_name='Оценка дизайна')),
                ('content', models.CharField(choices=[('1', 'Отлично'), ('2', 'Хорошо'), ('3', 'Сойдет'), ('4', 'Ужасно')], max_length=20, verbose_name='Оценка контента')),
                ('notice', models.BooleanField(default=False, verbose_name='Получать новости на e-mail')),
                ('contact', models.BooleanField(default=False, verbose_name='Разрешаю связаться по поводу отзыва')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес e-mail')),
                ('message', models.TextField(verbose_name='Отзыв')),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'db_table': 'Feedback',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 19, 2, 9, 22, 141106), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 19, 2, 9, 22, 141106), verbose_name='Дата'),
        ),
    ]
