# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-12-19 15:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20251219_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200, verbose_name='ФИО пациента')),
                ('appointment_date', models.DateField(verbose_name='Дата приёма')),
                ('appointment_time', models.CharField(choices=[('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00')], max_length=5, verbose_name='Время приёма')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Дата создания записи')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждена')),
            ],
            options={
                'verbose_name': 'запись на приём',
                'verbose_name_plural': 'записи на приём',
                'db_table': 'Appointments',
                'ordering': ['-appointment_date', 'appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО врача')),
                ('specialty', models.CharField(max_length=200, verbose_name='Специальность')),
                ('office', models.CharField(blank=True, max_length=50, null=True, verbose_name='Кабинет')),
                ('work_schedule', models.CharField(blank=True, max_length=200, null=True, verbose_name='График работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'врач',
                'verbose_name_plural': 'врачи',
                'db_table': 'Doctors',
                'ordering': ['specialty', 'full_name'],
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 19, 18, 53, 13, 266696), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 19, 18, 53, 13, 266696), verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctor', verbose_name='Врач'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set([('doctor', 'appointment_date', 'appointment_time')]),
        ),
    ]
